'use client';

import { useEffect, useState } from 'react';
import { Camera, ChevronLeft, ChevronRight, TreePine, Waves } from 'lucide-react';

const destinations = [
  { name: 'Pantai Wedi Ireng', eyebrow: '01 / Pesisir', text: 'Teluk tersembunyi dengan pasir terang dan air biru untuk membuka perjalanan.', image: '/images/hero-bg.png', icon: Waves },
  { name: 'Pantai Mustika', eyebrow: '02 / Pesisir', text: 'Ruang untuk menikmati angin laut, sarapan, dan momen pertama bersama tim.', image: '/images/hero-bg.png', icon: Waves },
  { name: 'Spot T', eyebrow: '03 / Horizon', text: 'Lanskap alam yang mengajak kita berhenti sejenak dari ritme kantor.', image: '/images/hero-bg.png', icon: Camera },
  { name: 'De Djawatan', eyebrow: '04 / Forest', text: 'Kanopi trembesi yang teduh, tempat cerita gathering berubah menjadi kenangan.', image: '/images/hero-bg.png', icon: TreePine },
];

export default function EventDetailsPage() {
  const [active, setActive] = useState(0);
  useEffect(() => { const timer = window.setInterval(() => setActive((value) => (value + 1) % destinations.length), 5000); return () => window.clearInterval(timer); }, []);
  const destination = destinations[active];
  return <div className="min-h-screen bg-background"><section className="surface-dark relative overflow-hidden px-6 py-24 lg:px-12" aria-roledescription="carousel" aria-label="Destinasi Banyuwangi"><div className="absolute inset-0 bg-[url('/images/hero-bg.png')] bg-cover bg-center opacity-30" aria-hidden="true" /><div className="relative mx-auto max-w-7xl"><div className="flex items-center justify-between"><p className="section-kicker text-secondary">The itinerary journal</p><span className="font-mono text-xs text-primary-foreground/60">{String(active + 1).padStart(2, '0')} / 04</span></div><div className="mt-20 grid min-h-[420px] items-end gap-8 lg:grid-cols-[1fr_auto]"><div><p className="section-kicker text-secondary">{destination.eyebrow}</p><h1 className="display-serif mt-5 max-w-4xl text-6xl leading-none text-primary-foreground sm:text-8xl">{destination.name}</h1><p className="mt-8 max-w-xl text-base leading-7 text-primary-foreground/75">{destination.text}</p></div><div className="flex gap-3"><button type="button" aria-label="Destinasi sebelumnya" onClick={() => setActive((active - 1 + destinations.length) % destinations.length)} className="grid size-12 place-items-center rounded-full border border-primary-foreground/30 hover:bg-secondary hover:text-primary"><ChevronLeft className="size-5" /></button><button type="button" aria-label="Destinasi berikutnya" onClick={() => setActive((active + 1) % destinations.length)} className="grid size-12 place-items-center rounded-full border border-primary-foreground/30 hover:bg-secondary hover:text-primary"><ChevronRight className="size-5" /></button></div></div><div className="mt-10 flex gap-2" role="tablist" aria-label="Pilih destinasi">{destinations.map((item, index) => <button key={item.name} type="button" role="tab" aria-selected={active === index} aria-label={item.name} onClick={() => setActive(index)} className={`h-1.5 rounded-full transition-all ${active === index ? 'w-14 bg-secondary' : 'w-6 bg-primary-foreground/30'}`} />)}</div></div></section><section className="surface-paper px-6 py-20 lg:px-12"><div className="mx-auto max-w-7xl"><p className="section-kicker">What awaits</p><h2 className="display-serif mt-5 text-5xl text-primary">Empat lanskap,<br />satu perjalanan.</h2><p className="mt-6 max-w-xl text-base leading-7 text-muted-foreground">Dari garis pantai ke hutan, setiap destinasi dipilih untuk membuat perjalanan terasa lengkap: bergerak, menikmati, dan bertumbuh bersama.</p></div></section></div>;
}
